spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: N.I.B
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553544
    password: 220605
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.OracleDialect

springdoc:
  api-docs:
    path: /api-docs